import 'package:flutter_lesson11/models/continents/south_america.dart';

import 'continents/africa.dart';
import 'continents/asia.dart';
import 'continents/australia.dart';
import 'continents/europe.dart';
import 'continents/north_america.dart';

class CountriesAndCapitals {
  // Asia
  static List<Asia> asiaList = [
    Asia(country: 'Афганистан', city: 'Кабул'),
    Asia(country: 'Армения', city: 'Ереван'),
    Asia(country: 'Азербайджан', city: 'Баку'),
    Asia(country: 'Бахрейн', city: 'Манама'),
    Asia(country: 'Бангладеш', city: 'Дакка'),
    Asia(country: 'Бутан', city: 'Тхимпху'),
    Asia(country: 'Бруней', city: 'Бандар-Сери-Бегаван'),
    Asia(country: 'Камбоджа', city: 'Пномпень'),
    Asia(country: 'Китай', city: 'Пекин'),
    Asia(country: 'Кипр', city: 'Никосия'),
    Asia(country: 'Грузия', city: 'Тбилиси'),
    Asia(country: 'Индия', city: 'Нью-Дели'),
    Asia(country: 'Индонезия', city: 'Джакарта'),
    Asia(country: 'Иран', city: 'Тегеран'),
    Asia(country: 'Ирак', city: 'Багдад'),
    Asia(country: 'Израиль', city: 'Иерусалим'),
    Asia(country: 'Япония', city: 'Токио'),
    Asia(country: 'Иордания', city: 'Амман'),
    Asia(country: 'Казахстан', city: 'Нур-Султан'),
    Asia(country: 'Кувейт', city: 'Кувейт'),
    Asia(country: 'Киргизия', city: 'Бишкек'),
    Asia(country: 'Лаос', city: 'Вьентьян'),
    Asia(country: 'Ливан', city: 'Бейрут'),
    Asia(country: 'Малайзия', city: 'Куала-Лумпур'),
    Asia(country: 'Мальдивы', city: 'Мале'),
    Asia(country: 'Монголия', city: 'Улан-Батор'),
    Asia(country: 'Мьянма (Бирма)', city: 'Нейпьидо'),
    Asia(country: 'Непал', city: 'Катманду'),
    Asia(country: 'Оман', city: 'Маскат'),
    Asia(country: 'Пакистан', city: 'Исламабад'),
    Asia(country: 'Филиппины', city: 'Манила'),
    Asia(country: 'Катар', city: 'Доха'),
    Asia(country: 'Россия', city: 'Москва'),
    Asia(country: 'Саудовская Аравия', city: 'Эр-Рияд'),
    Asia(country: 'Сингапур', city: 'Сингапур'),
    Asia(country: 'Южная Корея', city: 'Сеул'),
    Asia(country: 'Шри-Ланка', city: 'Коломбо'),
    Asia(country: 'Сирия', city: 'Дамаск'),
    Asia(country: 'Таджикистан', city: 'Душанбе'),
    Asia(country: 'Таиланд', city: 'Бангкок'),
    Asia(country: 'Турция', city: 'Анкара'),
    Asia(country: 'Туркменистан', city: 'Ашхабад'),
    Asia(country: 'Объединенные Арабские Эмираты', city: 'Абу-Даби'),
    Asia(country: 'Узбекистан', city: 'Ташкент'),
    Asia(country: 'Вьетнам', city: 'Ханой'),
    Asia(country: 'Йемен', city: 'Сана')
  ];

  // Europe
  static List<Europe> europeList = [
    Europe(country: 'Албания', city: 'Тирана'),
    Europe(country: 'Андорра', city: 'Андорра-ла-Велья'),
    Europe(country: 'Австрия', city: 'Вена'),
    Europe(country: 'Беларусь', city: 'Минск'),
    Europe(country: 'Бельгия', city: 'Брюссель'),
    Europe(country: 'Босния и Герцеговина', city: 'Сараево'),
    Europe(country: 'Болгария', city: 'София'),
    Europe(country: 'Хорватия', city: 'Загреб'),
    Europe(country: 'Кипр', city: 'Никосия'),
    Europe(country: 'Чехия', city: 'Прага'),
    Europe(country: 'Дания', city: 'Копенгаген'),
    Europe(country: 'Эстония', city: 'Таллин'),
    Europe(country: 'Финляндия', city: 'Хельсинки'),
    Europe(country: 'Франция', city: 'Париж'),
    Europe(country: 'Германия', city: 'Берлин'),
    Europe(country: 'Греция', city: 'Афины'),
    Europe(country: 'Венгрия', city: 'Будапешт'),
    Europe(country: 'Исландия', city: 'Рейкьявик'),
    Europe(country: 'Ирландия', city: 'Дублин'),
    Europe(country: 'Италия', city: 'Рим'),
    Europe(country: 'Латвия', city: 'Рига'),
    Europe(country: 'Литва', city: 'Вильнюс'),
    Europe(country: 'Люксембург', city: 'Люксембург'),
    Europe(country: 'Мальта', city: 'Валлетта'),
    Europe(country: 'Молдавия', city: 'Кишинёв'),
    Europe(country: 'Монако', city: 'Монако'),
    Europe(country: 'Черногория', city: 'Подгорица'),
    Europe(country: 'Нидерланды', city: 'Амстердам'),
    Europe(country: 'Северная Македония', city: 'Скопье'),
    Europe(country: 'Норвегия', city: 'Осло'),
    Europe(country: 'Польша', city: 'Варшава'),
    Europe(country: 'Португалия', city: 'Лиссабон'),
    Europe(country: 'Румыния', city: 'Бухарест'),
    Europe(country: 'Сан-Марино', city: 'Сан-Марино'),
    Europe(country: 'Сербия', city: 'Белград'),
    Europe(country: 'Словакия', city: 'Братислава'),
    Europe(country: 'Словения', city: 'Любляна'),
    Europe(country: 'Испания', city: 'Мадрид'),
    Europe(country: 'Швеция', city: 'Стокгольм'),
    Europe(country: 'Швейцария', city: 'Берн'),
    Europe(country: 'Украина', city: 'Киев'),
    Europe(country: 'Великобритания', city: 'Лондон'),
  ];

//Africa
  static List<Africa> africaList = [
    Africa(country: 'Алжир', city: 'Алжир'),
    Africa(country: 'Ангола', city: 'Луанда'),
    Africa(country: 'Бенин', city: 'Порто-Ново'),
    Africa(country: 'Ботсвана', city: 'Габороне'),
    Africa(country: 'Буркина-Фасо', city: 'Уагадугу'),
    Africa(country: 'Бурунди', city: 'Бужумбура'),
    Africa(country: 'Кабо-Верде', city: 'Прая'),
    Africa(country: 'Камерун', city: 'Яунде'),
    Africa(country: 'Центральноафриканская Республика', city: 'Банги'),
    Africa(country: 'Чад', city: 'Нджамена'),
    Africa(country: 'Коморы', city: 'Морони'),
    Africa(country: 'Конго', city: 'Браззавиль'),
    Africa(country: 'Демократическая Республика Конго', city: 'Киншаса'),
    Africa(country: 'Джибути', city: 'Джибути'),
    Africa(country: 'Египет', city: 'Каир'),
    Africa(country: 'Экваториальная Гвинея', city: 'Малабо'),
    Africa(country: 'Эритрея', city: 'Асмэра'),
    Africa(country: 'Эсватини', city: 'Мбабане'),
    Africa(country: 'Эфиопия', city: 'Аддис-Абеба'),
    Africa(country: 'Габон', city: 'Либревиль'),
    Africa(country: 'Гамбия', city: 'Банжул'),
    Africa(country: 'Гана', city: 'Аккра'),
    Africa(country: 'Гвинея', city: 'Конакри'),
    Africa(country: 'Гвинея-Бисау', city: 'Бисау'),
    Africa(country: 'Кот-д\'Ивуар', city: 'Ямусукро'),
    Africa(country: 'Кения', city: 'Найроби'),
    Africa(country: 'Лесото', city: 'Масеру'),
    Africa(country: 'Либерия', city: 'Монровия'),
    Africa(country: 'Ливия', city: 'Триполи'),
    Africa(country: 'Мадагаскар', city: 'Антананариву'),
    Africa(country: 'Малави', city: 'Лилонгве'),
    Africa(country: 'Мали', city: 'Бамако'),
    Africa(country: 'Мавритания', city: 'Нуакшот'),
    Africa(country: 'Маврикий', city: 'Порт-Луи'),
    Africa(country: 'Марокко', city: 'Рабат'),
    Africa(country: 'Мозамбик', city: 'Мапуту'),
    Africa(country: 'Намибия', city: 'Виндхук'),
    Africa(country: 'Нигер', city: 'Ниамей'),
    Africa(country: 'Нигерия', city: 'Абуджа'),
    Africa(country: 'Руанда', city: 'Кигали'),
    Africa(country: 'Сан-Томе и Принсипи', city: 'Сан-Томе'),
    Africa(country: 'Сенегал', city: 'Дакар'),
    Africa(country: 'Сейшельские Острова', city: 'Виктория'),
    Africa(country: 'Сьерра-Леоне', city: 'Фритаун'),
    Africa(country: 'Сомали', city: 'Могадишо'),
    Africa(country: 'Южная Африка', city: 'Претория'),
    Africa(country: 'Южный Судан', city: 'Джуба'),
    Africa(country: 'Судан', city: 'Хартум'),
    Africa(country: 'Танзания', city: 'Додома'),
    Africa(country: 'Того', city: 'Ломе'),
    Africa(country: 'Тунис', city: 'Тунис'),
    Africa(country: 'Уганда', city: 'Кампала'),
    Africa(country: 'Западная Сахара', city: 'Аюн-эль-Атрус'),
    Africa(country: 'Замбия', city: 'Лусака'),
    Africa(country: 'Зимбабве', city: 'Хараре'),
  ];

//Australia
  static List<Australia> australiaList = [
    Australia(country: 'Австралия', city: 'Канберра'),
    Australia(country: 'Вануату', city: 'Порт-Вила'),
    Australia(country: 'Кирибати', city: 'Южная Тарава'),
    Australia(country: 'Маршалловы Острова', city: 'Маджуро'),
    Australia(country: 'Микронезия', city: 'Паликир'),
    Australia(country: 'Науру', city: 'Ярен'),
    Australia(country: 'Новая Зеландия', city: 'Веллингтон'),
    Australia(country: 'Палау', city: 'Мелекеок'),
    Australia(country: 'Папуа — Новая Гвинея', city: 'Порт-Морсби'),
    Australia(country: 'Соломоновы Острова', city: 'Хониара'),
    Australia(country: 'Тонга', city: 'Нукуалофа'),
    Australia(country: 'Тувалу', city: 'Фунафути'),
    Australia(country: 'Фиджи', city: 'Сува'),
    Australia(country: 'Шри-Ланка', city: 'Коломбо'),
  ];

//North America
  static List<NorthAmerica> northAmericaList = [
    NorthAmerica(country: 'Антигуа и Барбуда', city: 'Сент-Джонс'),
    NorthAmerica(country: 'Багамские Острова', city: 'Нассау'),
    NorthAmerica(country: 'Барбадос', city: 'Бриджтаун'),
    NorthAmerica(country: 'Белиз', city: 'Бельмопан'),
    NorthAmerica(country: 'Канада', city: 'Оттава'),
    NorthAmerica(country: 'Коста-Рика', city: 'Сан-Хосе'),
    NorthAmerica(country: 'Куба', city: 'Гавана'),
    NorthAmerica(country: 'Доминика', city: 'Розо'),
    NorthAmerica(country: 'Доминиканская Республика', city: 'Санто-Доминго'),
    NorthAmerica(country: 'Сальвадор', city: 'Сан-Сальвадор'),
    NorthAmerica(country: 'Гренада', city: 'Сент-Джорджес'),
    NorthAmerica(country: 'Гватемала', city: 'Гватемала'),
    NorthAmerica(country: 'Гаити', city: 'Порт-о-Пренс'),
    NorthAmerica(country: 'Гондурас', city: 'Тегусигальпа'),
    NorthAmerica(country: 'Ямайка', city: 'Кингстон'),
    NorthAmerica(country: 'Мексика', city: 'Мехико'),
    NorthAmerica(country: 'Никарагуа', city: 'Манагуа'),
    NorthAmerica(country: 'Панама', city: 'Панама'),
    NorthAmerica(country: 'Сент-Китс и Невис', city: 'Бастер'),
    NorthAmerica(country: 'Сент-Люсия', city: 'Кастри'),
    NorthAmerica(country: 'Сент-Винсент и Гренадины', city: 'Кингстаун'),
    NorthAmerica(country: 'Тринидад и Тобаго', city: 'Порт-оф-Спейн'),
    NorthAmerica(country: 'США', city: 'Вашингтон, округ Колумбия'),
  ];

//South America
  static List<SouthAmerica> southAmericaList = [
    SouthAmerica(country: 'Аргентина', city: 'Буэнос-Айрес'),
    SouthAmerica(country: 'Боливия', city: 'Сукре'),
    SouthAmerica(country: 'Бразилия', city: 'Бразилиа'),
    SouthAmerica(country: 'Чили', city: 'Сантьяго'),
    SouthAmerica(country: 'Колумбия', city: 'Богота'),
    SouthAmerica(country: 'Эквадор', city: 'Кито'),
    SouthAmerica(country: 'Гайана', city: 'Джорджтаун'),
    SouthAmerica(country: 'Парагвай', city: 'Асунсьон'),
    SouthAmerica(country: 'Перу', city: 'Лима'),
    SouthAmerica(country: 'Суринам', city: 'Парамарибо'),
    SouthAmerica(country: 'Уругвай', city: 'Монтевидео'),
    SouthAmerica(country: 'Венесуэла', city: 'Каракас'),
  ];
}
